### PR TITLE
Upgrades protos to TM 0.26.1

### PR DESCRIPTION
**Pull request by davebryson**
This pull request updates `types.js` and `index.d.ts` to support Tendermint 0.26.1.  The `protos` directory is out of date.  I probably should have deleted the old proto files but I didn't want to step on too many toes.

I've tested this with Tendermint 0.26.1 against the tests and the counter.js app - all seem to work fine.  There are 3 errors related to signatures in the `test/fixtures.js`, I assume these are do to protocol updates.

I have a separate `quasi-automated` build/update process for protos that I'll push to a separate repo shortly.

### CODE REVIEW

**Comment by zramsay** [comment]
thanks! standby for review

**Review by melekes — APPROVED** [review]

**Comment by melekes** [comment]
Awesome. Thanks!

**Comment by zramsay** [comment]
looks like this broke 3 tests

**Comment by davebryson** [comment]
> looks like this broke 3 tests

I don't know about the 0.26.3 version (that wasn't mine),  but I mentioned in my original pull request that there were 3 errors (I believe) related to 'signatures' in the fixtures.  I assumed they may have changed due to Amino prefixes.   Yes... I'll admit I was lazy and didn't check 😳

**Comment by zramsay** [comment]
ah, gotcha. i've reverted master to get the tests passing and now we have the CI up and running. it seems this PR broke 3 tests and #27 broke an additional one

**Pull request merged**
