### PR TITLE
Update ABCI types to Tendermint v0.26.3

### PR DESCRIPTION
**Pull request by marypreethi12**

### CODE REVIEW

**Comment by zramsay** [comment]
thanks! standby for review. Might need to rebase on #26

**Comment by melekes** [comment]
Can we get this rebased against latest master? Thank you

**Review by melekes — APPROVED** [review]

**Comment by melekes** [comment]
Awesome! Thanks

**Comment by zramsay** [comment]
https://github.com/tendermint/js-abci/commit/333f6a8ca80f940a43e76d63c300ee9740077742#diff-dfd7851767dfe20984bfb77eb69df4e9R8610

a couple lines left over from a rebase, caught by CI

**Comment by zramsay** [comment]
i think we'll have to revert this PR, looks like it broke the tests

**Comment by zramsay** [comment]
yup, reverted. could you re-open this PR now that there's a CI that will test the changes

**Pull request merged**
