### PR TITLE
Update port in example/app.js to match the docs

### PR DESCRIPTION
**Pull request by amazingandyyy**
The official docs is using 46658 port, 

refer to docs here: https://tendermint.readthedocs.io/en/master/getting-started.html#counterjs-example-in-another-language

### CODE REVIEW

**Comment by amazingandyyy** [comment]
my misunderstanding, it means to be 46657 here

**Comment by jbibla** [comment]
@zramsay ?

**Comment by amazingandyyy** [comment]
hey so it turns out, `node example/app.js` doesn't work, the `tendermint node` doesn't stream the state... and `port 46657` also doesn't work(no response), can anyone confirm the example work? or what mistake here I may make?

thank you

**Comment by zramsay** [comment]
it's possible this example needs to be updated, see #13

**Comment by ameeuw** [comment]
I am having the exact problems as @amazingandyyy - tendermint node does not stream the state and is not available for commiting txs..
Is there anybody able to update this example? Maybe we can dissect it ourselves... It seems to be the only one out there and is already 11 months old..

**Comment by amazingandyyy** [comment]
@ameeuw yeah that's a little stressful, I personally still want to build a chain in node, but if this issue is still around, I may switch to golang eventually(altho it's not bad).

**Comment by zramsay** [comment]
@amazingandyyy @ameeuw check out https://github.com/keppel/lotion

**Comment by amazingandyyy** [comment]
@zramsay it looks awesome thanks

**Pull request closed without merging**
