### PR TITLE
protos updated according to tendermint v0.33.6

### PR DESCRIPTION
**Pull request by radsal**

### CODE REVIEW

**Review by tac0turtle — APPROVED** [review]
utACK, thankyou for this PR. Please keep in mind, we do not actively maintain this library so there are not assurances that other things are correct.

**Comment by radsal** [comment]
@marbar3778 Thanks for the information. I was able to run the existing tests locally. Who can review and merge this?

**Comment by tac0turtle** [comment]
@alessio can you help here?

**Comment by radsal** [comment]
Any update on this?

**Pull request merged**
