### PR TITLE
fixed type errors in the test 

### PR DESCRIPTION
**Pull request by marypreethi12**
however 3 tests are failing , may be something to do with fixtures, can somebody suggest?

### CODE REVIEW

**Review by melekes — APPROVED** [review]

**Comment by melekes** [comment]
@marypreethi12 can we get this rebased against latest master? thank you

**Comment by melekes** [comment]
Looks like tests are failing.

**Comment by zramsay** [comment]
@mappum will be taking a look

**Comment by melekes** [comment]
> @mappum will be taking a look

does not look like it

**Comment by pasiphae00** [comment]
**EDIT:** my apologies, did not see @melekes recent reply. You can ignore this :)

Any updates on this? Have been using @marypreethi12's fork for development (and in some test-networks) with Tendermint Core `v0.26.4` with no detected issues.

I cannot comment on the status of the failing tests, however I have noticed no issues so far. (Except the ABCI connection failing under extremely high load, although that is likely an issue with my application.)

**Comment by mappum** [comment]
All that had to be updated was a test fixture which was different due to changes in Amino.

I'll publish a release shortly.

**Comment by mappum** [comment]
@marypreethi12 Thanks for keeping this up-to-date by the way!

**Comment by mappum** [comment]
These changes are now released in `abci@5` (a semver major version change, since this package is now incompatible with older versions of Tendermint).

**Comment by pasiphae00** [comment]
Great, thanks @mappum and @marypreethi12.

Currently using this with tendermint v0.27 with no issues detected. The README says it is compatible with >=v0.19 however. Does that need to be updated?

Also can we assume this will not work with the most recent Tendermint release (0.29, I believe)?

I'll try it out anyway with 0.29 and see what happens.

**EDIT:** quick test indicates `abci@5` works with Tendermint v0.29

**Comment by mappum** [comment]
@hrharder I don't see any changes to ABCI in recent versions of Tendermint so I believe it should be fully compatible

**Comment by pasiphae00** [comment]
Great, thanks. Just started up a test-net with [my ABCI app](https://github.com/ParadigmFoundation/ParadigmCore) using TM v0.29, and `abci@5.0.1`, no issues so far.

Might want to update the readme in the next patch? 🤷‍♂️

**Pull request merged**
